#
# Site Command.  Use to run any command.
#
name: Run command
on:
  workflow_call:
    inputs:

      working_directory:
        required: true
        type: string
        description: The path to run the command in.

      command:
        type: string
        description: The command to run.
        required: true

      github_runs_on:
        type: string
        default: ubuntu-latest
        description: The label of the runner you wish to use.

      env:
        type: string
        default: Environment
        description: |
          A string of environment variables to set for the command run. To alter the summary, see https://github.com/jonpugh/goatscripts/blob/main/src/run-with-summary 

jobs:
  run-command:
    name: Run command
    runs-on: ${{ inputs.github_runs_on }}
    steps:
      - uses: jonpugh/goatscripts@main

      - name: run command
        env:
          SUCCESS: ":white_check_mark: Command complete"
          ERROR: ":x: Command failed"
          SUMMARY: |
            - Root: `${{ inputs.working_directory }}`
        working-directory: ${{ inputs.working_directory }}
        run: |
          ${{ inputs.env }}
          run-with-summary ${{ inputs.command }}
