#
#  Site Deploy
#  via DDEV.
#
on:
  workflow_call:
    inputs:

      git_repository:
        default: ${{ github.event.repository.clone_url }}
        type: string
        description: The repository to deploy.

      git_reference:
        default: ${{ github.head_ref || github.ref_name }}
        type: string
        description: The git reference to deploy.

      git_root:
        required: true
        type: string
        description: The path to clone the repository into, relative to the runner workspace. Use absolute paths when running a persistent server.

      start_command:
        default: ddev start
        type: string
        description: The command to launch the site servers.

      run_start_command:
        default: true
        type: boolean
        description: Whether to run the ddev start command.

      # AKA Sync or Install.
      prepare_command:
        default: ddev drush site:install
        type: string
        description: The command to run to prepare site data, such as a sync script, migration or install profile.

      run_prepare_command:
        # False by default to prevent data loss. If there is no data, the prepare command will still be run.
        default: false
        type: boolean
        description: Whether to run the prepare command.

      deploy_command:
        default: ddev drush deploy
        type: string
        description: The command to run after deploying new code.

      run_deploy_command:
        default: true
        type: boolean
        description: Whether to run the deploy command.

      ddev_project_name:
        type: string
        default: ${{ github.event.repository.name }}
        description: The ddev project name for this environment. Must be unique on this server. Will be used for the default domain using {ddev_project_name}.{ddev_project_tld}.

      ddev_project_tld:
        type: string
        description: The top-level domain used for the environment.

      ddev_config:
        type: string
        description: Extra ddev configuration for this environment to write to .ddev/config.zzz.workflow.yaml. Use to apply environment-specific configuration, additional_fqdns, etc.

      ddev_config_filename:
        default: "config.zzz.hosting.yaml"
        type: string
        description: The file to create in the .ddev folder to store the ddev configuration.

      github_runs_on:
        type: string
        default: ubuntu-latest
        description: The label of the runner you wish to use.

      github_environment_name:
        type: string
        default: ${{ github.head_ref || github.ref_name }}
        description: The string to use as the GitHub environment.

      github_environment_url:
        type: string
        default: ${{ inputs.ddev_project_name }}.${{ inputs.ddev_project_tld }}
        description: The URL to use for the GitHub environment.

env:
  PATH: ${{ env.GITHUB_WORKSPACE }}/goatscripts/src:/usr/local/bin:/usr/bin:/bin

jobs:
  deploy-code:
    name: Deploy Code
    runs-on: ${{ inputs.github_runs_on }}

    steps:
    
      - name: Clone code
        run: |
          echo $PATH
          if [[ ! -d ${{ inputs.git_root }} ]]; then
            git clone ${{ inputs.git_repository }} ${{ inputs.git_root }}
          fi
          cd ${{ inputs.git_root }}
          git checkout ${{ inputs.git_reference }}
          echo -----------------------------
          echo "Cloned code to ${{ inputs.git_root }}"

  start-site:
    name: Start site
    runs-on: ${{ inputs.github_runs_on }}
    needs: deploy-code

    steps:
      - name: Check DDEV Installation
        run: |
          if [[ `command -v ddev`  ]]; then
            echo "DDEV is already installed."
            echo "DDEV_INSTALLED=true" >> $GITHUB_ENV
          else
            echo "DDEV is not installed."
            echo "DDEV_INSTALLED=false" >> $GITHUB_ENV
          fi
          
          if [[ `sudo pwd`  ]]; then
            echo "Runner has sudo access."
            echo "RUNNER_SUDO=true" >> $GITHUB_ENV
          else
            echo "Runner does not have sudo access."
            echo "RUNNER_SUDO=false" >> $GITHUB_ENV
          fi
          
          if [[ $DDEV_INSTALLED == "false" && $RUNNER_SUDO == "false" ]]; then
            echo "Unable to continue. DDEV cannot be installed without sudo access."
            exit 1
          fi

      - name: Configure DDEV
        working-directory: ${{ inputs.git_root }}/.ddev
        run: |
          echo "# DDEV Config created by GitHub workflow https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}" >  ${{ inputs.ddev_config_filename }}
          echo "name: ${{ inputs.ddev_project_name }}" >> ${{ inputs.ddev_config_filename }}
          echo "project_tld: ${{ inputs.ddev_project_tld }}" >> ${{ inputs.ddev_config_filename }}
          echo "${{ inputs.ddev_config }}" >> ${{ inputs.ddev_config_filename }}

      # Install DDEV, if needed.
      # This only works for runners by sudo users. Don't run it if ddev is already installed.
      - name: Setup DDEV
        uses: ddev/github-action-setup-ddev@v1
        if: ${{ env.DDEV_INSTALLED == 'false' }}
        with:
          autostart: false

      - uses: actions/checkout@v4
        with:
          repository: 'jonpugh/goatscripts'
          ref: 'v1.0.0'
          path: .scripts
          
      - name: Start site
        working-directory: ${{ inputs.git_root }}
        if: ${{ inputs.run_start_command }}
        env:
          HEADER: Started DDEV Site
        run: |
          ls -la
          .scripts/src/run-with-summary ${{ inputs.start_command }}

  # Import, sync, install, etc.
  prepare-data:
    name: Prepare data
    runs-on: ${{ inputs.github_runs_on }}
    needs: start-site

    # Show links to this environment in the UI to the site.
    environment:
      name: ${{ inputs.github_environment_name }}
      url: "${{ inputs.github_environment_url }}"

    steps:

      - uses: actions/checkout@v4
        name: Install scripts
        with:
          repository: 'jonpugh/goatscripts'
          ref: 'v1.0.0'
          path: goatscripts
          
      - name: Prepare data
        working-directory: ${{ inputs.git_root }}
        if: ${{ inputs.run_prepare_command }}
        run: |
          ls -la 
          ./run-with-summary ${{ inputs.prepare_command }}

      - name: Deploy command
        working-directory: ${{ inputs.git_root }}
        if: ${{ inputs.run_deploy_command }}
        run: |
          .scripts/src/run-with-summary ${{ inputs.deploy_command }}
