name: Preview Sites
on:
  pull_request:

env:
  # https://github.com/operations-project/github-runner-starter/settings/secrets/actions/JONPUGH_GITHUB_TOKEN_ADMIN
  GITHUB_TOKEN: "${{ secrets.OPERATIONS_GITHUB_TOKEN_ADMIN }}"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number }}
  cancel-in-progress: false

jobs:
  # This emulates a persistent server. The ddev.site.deploy.yml jobs require one.
  # This job runs the rest. It will stay running until the last job is complete.
  create-server:
    name: Launch a test server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: 'operations-project/github-runner-starter'
          ref: 'v1.2.1'

      # Kick off the runner script over and over until there are no more queued jobs.
      - name: "Launch runner script."

        run: |
          while [[ $(curl -s -H "Authorization: token ${GITHUB_TOKEN}" "https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/jobs" | jq -r '.jobs[] | select(.status=="queued") | .id' | wc -l) -gt 0 ]]; do
            ./github-runner-starter \
            --run \
            --name=github.actions.runner.${{ github.run_id }}.${{ matrix.runner }} \
            --labels=github.actions.runner.${{ github.run_id }} \
            --config-sh-options=--ephemeral
          sleep 4
          done

  create-site:
    name: Create Preview Site
    uses: operations-project/github-action-ddev-runner/.github/workflows/ops.site.deploy.ddev.yml@feature/run-with-summary
    with:

      # Configure your site  here.
      git_root: /home/runner/ourproject/pr${{ github.event.number }}

      # Must be unique per server.
      ddev_project_name: ourproject.pr${{ github.event.number }}

      # Used to create a system domain.
      ddev_project_tld: sites.thinkdrop.net

      # Tell the remote workflow what to run on.
      github_runs_on: github.actions.runner.${{ github.run_id }}

      # Define the github environment name, to be displayed in the UI.
      github_environment_name: pr${{ github.event.number }}

      # Define a github environment url, a link to be shown on the pull request.
      github_environment_url: http://pr${{ github.event.number }}.sites.thinkdrop.net

      # To persist a site's data, set "run_prepare_command" to false.
      run_prepare_command: true
      prepare_command: echo "Preparing site..."

      # Command to run after deploying code.
      deploy_command: ddev exec echo "Hello from $(hostname)!"

      # Additional ddev config to apply to the environment.
      # Will be saved to .ddev/config.zzz.runner.yaml
      ddev_config: |
        additional_fqdns:
          - admin.pr${{ github.event.number }}.sites.thinkdrop.net
          - ddev-runner.ddev.site

  test-site:
    name: Run tests
    needs: create-site
    runs-on: github.actions.runner.${{ github.run_id }}
    steps:

      - uses: actions/checkout@v4
        with:
          repository: 'jonpugh/goatscripts'
          ref: 'main'
          path: goatscripts

      - name: Set environment
        run: |
          echo "$GITHUB_WORKSPACE/goatscripts/src" >> $GITHUB_PATH

      - name: Check homepage for Hello World.
        env:
          SUCCESS: "Tests passed! DDEV webserver is online. :boom:"
          ERROR: "Unable to load DDEV website. :x:"
        run: |
          run-with-summary curl https://ddev-runner.ddev.site
          curl -s https://ddev-runner.ddev.site | grep "Hello World!"
# Not writing ddev config yet.
#          curl -s http://pr${{ github.event.number }}.sites.thinkdrop.net
